// Generated by gencpp from file amrl_msgs/BBox2DArrayMsg.msg
// DO NOT EDIT!


#ifndef AMRL_MSGS_MESSAGE_BBOX2DARRAYMSG_H
#define AMRL_MSGS_MESSAGE_BBOX2DARRAYMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <amrl_msgs/BBox2DMsg.h>

namespace amrl_msgs
{
template <class ContainerAllocator>
struct BBox2DArrayMsg_
{
  typedef BBox2DArrayMsg_<ContainerAllocator> Type;

  BBox2DArrayMsg_()
    : header()
    , bboxes()  {
    }
  BBox2DArrayMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , bboxes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::amrl_msgs::BBox2DMsg_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::amrl_msgs::BBox2DMsg_<ContainerAllocator> >> _bboxes_type;
  _bboxes_type bboxes;





  typedef boost::shared_ptr< ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator> const> ConstPtr;

}; // struct BBox2DArrayMsg_

typedef ::amrl_msgs::BBox2DArrayMsg_<std::allocator<void> > BBox2DArrayMsg;

typedef boost::shared_ptr< ::amrl_msgs::BBox2DArrayMsg > BBox2DArrayMsgPtr;
typedef boost::shared_ptr< ::amrl_msgs::BBox2DArrayMsg const> BBox2DArrayMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator1> & lhs, const ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.bboxes == rhs.bboxes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator1> & lhs, const ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace amrl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e64d4da35041980e61fafff1494c211";
  }

  static const char* value(const ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e64d4da35041980ULL;
  static const uint64_t static_value2 = 0xe61fafff1494c211ULL;
};

template<class ContainerAllocator>
struct DataType< ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amrl_msgs/BBox2DArrayMsg";
  }

  static const char* value(const ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"BBox2DMsg[] bboxes\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: amrl_msgs/BBox2DMsg\n"
"string label\n"
"float32 conf\n"
"float32[] xyxy\n"
;
  }

  static const char* value(const ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.bboxes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BBox2DArrayMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amrl_msgs::BBox2DArrayMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "bboxes[]" << std::endl;
    for (size_t i = 0; i < v.bboxes.size(); ++i)
    {
      s << indent << "  bboxes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::amrl_msgs::BBox2DMsg_<ContainerAllocator> >::stream(s, indent + "    ", v.bboxes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMRL_MSGS_MESSAGE_BBOX2DARRAYMSG_H
