// Generated by gencpp from file amrl_msgs/ColoredText.msg
// DO NOT EDIT!


#ifndef AMRL_MSGS_MESSAGE_COLOREDTEXT_H
#define AMRL_MSGS_MESSAGE_COLOREDTEXT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <amrl_msgs/Point2D.h>

namespace amrl_msgs
{
template <class ContainerAllocator>
struct ColoredText_
{
  typedef ColoredText_<ContainerAllocator> Type;

  ColoredText_()
    : start()
    , color(0)
    , size_em(0.0)
    , text()  {
    }
  ColoredText_(const ContainerAllocator& _alloc)
    : start(_alloc)
    , color(0)
    , size_em(0.0)
    , text(_alloc)  {
  (void)_alloc;
    }



   typedef  ::amrl_msgs::Point2D_<ContainerAllocator>  _start_type;
  _start_type start;

   typedef uint32_t _color_type;
  _color_type color;

   typedef float _size_em_type;
  _size_em_type size_em;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _text_type;
  _text_type text;





  typedef boost::shared_ptr< ::amrl_msgs::ColoredText_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amrl_msgs::ColoredText_<ContainerAllocator> const> ConstPtr;

}; // struct ColoredText_

typedef ::amrl_msgs::ColoredText_<std::allocator<void> > ColoredText;

typedef boost::shared_ptr< ::amrl_msgs::ColoredText > ColoredTextPtr;
typedef boost::shared_ptr< ::amrl_msgs::ColoredText const> ColoredTextConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amrl_msgs::ColoredText_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amrl_msgs::ColoredText_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::amrl_msgs::ColoredText_<ContainerAllocator1> & lhs, const ::amrl_msgs::ColoredText_<ContainerAllocator2> & rhs)
{
  return lhs.start == rhs.start &&
    lhs.color == rhs.color &&
    lhs.size_em == rhs.size_em &&
    lhs.text == rhs.text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::amrl_msgs::ColoredText_<ContainerAllocator1> & lhs, const ::amrl_msgs::ColoredText_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace amrl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::amrl_msgs::ColoredText_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amrl_msgs::ColoredText_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amrl_msgs::ColoredText_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amrl_msgs::ColoredText_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amrl_msgs::ColoredText_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amrl_msgs::ColoredText_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amrl_msgs::ColoredText_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d76c83017bb05a885d6115e7c920d0c6";
  }

  static const char* value(const ::amrl_msgs::ColoredText_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd76c83017bb05a88ULL;
  static const uint64_t static_value2 = 0x5d6115e7c920d0c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::amrl_msgs::ColoredText_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amrl_msgs/ColoredText";
  }

  static const char* value(const ::amrl_msgs::ColoredText_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amrl_msgs::ColoredText_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Point2D start\n"
"uint32 color\n"
"float32 size_em\n"
"string text\n"
"\n"
"================================================================================\n"
"MSG: amrl_msgs/Point2D\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::amrl_msgs::ColoredText_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amrl_msgs::ColoredText_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.color);
      stream.next(m.size_em);
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ColoredText_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amrl_msgs::ColoredText_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amrl_msgs::ColoredText_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    s << std::endl;
    Printer< ::amrl_msgs::Point2D_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
    s << indent << "color: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.color);
    s << indent << "size_em: ";
    Printer<float>::stream(s, indent + "  ", v.size_em);
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMRL_MSGS_MESSAGE_COLOREDTEXT_H
