// Generated by gencpp from file amrl_msgs/ColoredArc2D.msg
// DO NOT EDIT!


#ifndef AMRL_MSGS_MESSAGE_COLOREDARC2D_H
#define AMRL_MSGS_MESSAGE_COLOREDARC2D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <amrl_msgs/Point2D.h>

namespace amrl_msgs
{
template <class ContainerAllocator>
struct ColoredArc2D_
{
  typedef ColoredArc2D_<ContainerAllocator> Type;

  ColoredArc2D_()
    : center()
    , radius(0.0)
    , start_angle(0.0)
    , end_angle(0.0)
    , color(0)  {
    }
  ColoredArc2D_(const ContainerAllocator& _alloc)
    : center(_alloc)
    , radius(0.0)
    , start_angle(0.0)
    , end_angle(0.0)
    , color(0)  {
  (void)_alloc;
    }



   typedef  ::amrl_msgs::Point2D_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef float _radius_type;
  _radius_type radius;

   typedef float _start_angle_type;
  _start_angle_type start_angle;

   typedef float _end_angle_type;
  _end_angle_type end_angle;

   typedef uint32_t _color_type;
  _color_type color;





  typedef boost::shared_ptr< ::amrl_msgs::ColoredArc2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amrl_msgs::ColoredArc2D_<ContainerAllocator> const> ConstPtr;

}; // struct ColoredArc2D_

typedef ::amrl_msgs::ColoredArc2D_<std::allocator<void> > ColoredArc2D;

typedef boost::shared_ptr< ::amrl_msgs::ColoredArc2D > ColoredArc2DPtr;
typedef boost::shared_ptr< ::amrl_msgs::ColoredArc2D const> ColoredArc2DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amrl_msgs::ColoredArc2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amrl_msgs::ColoredArc2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::amrl_msgs::ColoredArc2D_<ContainerAllocator1> & lhs, const ::amrl_msgs::ColoredArc2D_<ContainerAllocator2> & rhs)
{
  return lhs.center == rhs.center &&
    lhs.radius == rhs.radius &&
    lhs.start_angle == rhs.start_angle &&
    lhs.end_angle == rhs.end_angle &&
    lhs.color == rhs.color;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::amrl_msgs::ColoredArc2D_<ContainerAllocator1> & lhs, const ::amrl_msgs::ColoredArc2D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace amrl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::amrl_msgs::ColoredArc2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amrl_msgs::ColoredArc2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amrl_msgs::ColoredArc2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amrl_msgs::ColoredArc2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amrl_msgs::ColoredArc2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amrl_msgs::ColoredArc2D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amrl_msgs::ColoredArc2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cca4be38df37d86344ae953f24de0bef";
  }

  static const char* value(const ::amrl_msgs::ColoredArc2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcca4be38df37d863ULL;
  static const uint64_t static_value2 = 0x44ae953f24de0befULL;
};

template<class ContainerAllocator>
struct DataType< ::amrl_msgs::ColoredArc2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amrl_msgs/ColoredArc2D";
  }

  static const char* value(const ::amrl_msgs::ColoredArc2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amrl_msgs::ColoredArc2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Circular arc section.\n"
"Point2D center\n"
"float32 radius\n"
"float32 start_angle\n"
"float32 end_angle\n"
"uint32 color\n"
"================================================================================\n"
"MSG: amrl_msgs/Point2D\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::amrl_msgs::ColoredArc2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amrl_msgs::ColoredArc2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.center);
      stream.next(m.radius);
      stream.next(m.start_angle);
      stream.next(m.end_angle);
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ColoredArc2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amrl_msgs::ColoredArc2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amrl_msgs::ColoredArc2D_<ContainerAllocator>& v)
  {
    s << indent << "center: ";
    s << std::endl;
    Printer< ::amrl_msgs::Point2D_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
    s << indent << "start_angle: ";
    Printer<float>::stream(s, indent + "  ", v.start_angle);
    s << indent << "end_angle: ";
    Printer<float>::stream(s, indent + "  ", v.end_angle);
    s << indent << "color: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMRL_MSGS_MESSAGE_COLOREDARC2D_H
