# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from amrl_msgs/ColoredLine2D.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import amrl_msgs.msg

class ColoredLine2D(genpy.Message):
  _md5sum = "f09bffbeb5ba52952062cabb27c95439"
  _type = "amrl_msgs/ColoredLine2D"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Point2D p0
Point2D p1
uint32 color

================================================================================
MSG: amrl_msgs/Point2D
float32 x
float32 y
"""
  __slots__ = ['p0','p1','color']
  _slot_types = ['amrl_msgs/Point2D','amrl_msgs/Point2D','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       p0,p1,color

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ColoredLine2D, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.p0 is None:
        self.p0 = amrl_msgs.msg.Point2D()
      if self.p1 is None:
        self.p1 = amrl_msgs.msg.Point2D()
      if self.color is None:
        self.color = 0
    else:
      self.p0 = amrl_msgs.msg.Point2D()
      self.p1 = amrl_msgs.msg.Point2D()
      self.color = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4fI().pack(_x.p0.x, _x.p0.y, _x.p1.x, _x.p1.y, _x.color))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.p0 is None:
        self.p0 = amrl_msgs.msg.Point2D()
      if self.p1 is None:
        self.p1 = amrl_msgs.msg.Point2D()
      end = 0
      _x = self
      start = end
      end += 20
      (_x.p0.x, _x.p0.y, _x.p1.x, _x.p1.y, _x.color,) = _get_struct_4fI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4fI().pack(_x.p0.x, _x.p0.y, _x.p1.x, _x.p1.y, _x.color))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.p0 is None:
        self.p0 = amrl_msgs.msg.Point2D()
      if self.p1 is None:
        self.p1 = amrl_msgs.msg.Point2D()
      end = 0
      _x = self
      start = end
      end += 20
      (_x.p0.x, _x.p0.y, _x.p1.x, _x.p1.y, _x.color,) = _get_struct_4fI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4fI = None
def _get_struct_4fI():
    global _struct_4fI
    if _struct_4fI is None:
        _struct_4fI = struct.Struct("<4fI")
    return _struct_4fI
