# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from amrl_msgs/ColoredArc2D.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import amrl_msgs.msg

class ColoredArc2D(genpy.Message):
  _md5sum = "cca4be38df37d86344ae953f24de0bef"
  _type = "amrl_msgs/ColoredArc2D"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Circular arc section.
Point2D center
float32 radius
float32 start_angle
float32 end_angle
uint32 color
================================================================================
MSG: amrl_msgs/Point2D
float32 x
float32 y
"""
  __slots__ = ['center','radius','start_angle','end_angle','color']
  _slot_types = ['amrl_msgs/Point2D','float32','float32','float32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       center,radius,start_angle,end_angle,color

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ColoredArc2D, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.center is None:
        self.center = amrl_msgs.msg.Point2D()
      if self.radius is None:
        self.radius = 0.
      if self.start_angle is None:
        self.start_angle = 0.
      if self.end_angle is None:
        self.end_angle = 0.
      if self.color is None:
        self.color = 0
    else:
      self.center = amrl_msgs.msg.Point2D()
      self.radius = 0.
      self.start_angle = 0.
      self.end_angle = 0.
      self.color = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5fI().pack(_x.center.x, _x.center.y, _x.radius, _x.start_angle, _x.end_angle, _x.color))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.center is None:
        self.center = amrl_msgs.msg.Point2D()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.center.x, _x.center.y, _x.radius, _x.start_angle, _x.end_angle, _x.color,) = _get_struct_5fI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5fI().pack(_x.center.x, _x.center.y, _x.radius, _x.start_angle, _x.end_angle, _x.color))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.center is None:
        self.center = amrl_msgs.msg.Point2D()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.center.x, _x.center.y, _x.radius, _x.start_angle, _x.end_angle, _x.color,) = _get_struct_5fI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5fI = None
def _get_struct_5fI():
    global _struct_5fI
    if _struct_5fI is None:
        _struct_5fI = struct.Struct("<5fI")
    return _struct_5fI
